-- Your SQL goes here

CREATE TABLE time_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  task_id INTEGER NOT NULL,
  note text NULL DEFAULT NULL,
  created_at DATETIME NOT NULL,
  ended_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (task_id)
  REFERENCES tasks (id)
     ON UPDATE CASCADE
     ON DELETE CASCADE
 );
-- ALTER TABLE sprints ADD COLUMN active_time_entry_id INTEGER NULL REFERENCES time_entries (id) ON UPDATE CASCADE ON DELETE CASCADE,
ALTER TABLE sprints ADD COLUMN active_task_id INTEGER NULL REFERENCES tasks (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE sprints ADD COLUMN active_task_started_at DATETIME NULL DEFAULT NULL;
ALTER TABLE sprints ADD COLUMN active_task_note TEXT NULL DEFAULT NULL;
